language: php

dist: trusty

php:
    - '7.3'

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

env:
    global:
        - APP_ENV=test
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"
# Download and configure Symfony webserver
    - echo "Downloading Symfony CLI" "Sylius"
    - |
        if [ ! -f $SYLIUS_CACHE_DIR/symfony ]; then
            wget https://get.symfony.com/cli/installer -O - | bash
            mv ~/.symfony/bin/symfony $SYLIUS_CACHE_DIR
        fi
        $SYLIUS_CACHE_DIR/symfony version

install:
    - composer install --no-interaction --prefer-dist
    - (cd tests/Application && yarn install)

before_script:
    - (cd tests/Application && bin/console doctrine:database:create -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create -vvv)
    - (cd tests/Application && bin/console assets:install public -vvv)
    - (cd tests/Application && bin/console cache:warmup -vvv)
    - (cd tests/Application && yarn build)

    # Run Chrome
    -  google-chrome --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222

    # Run webserver
    - (cd tests/Application && $SYLIUS_CACHE_DIR/symfony server:start --dir=public --force-php-discovery --daemon)
script:
    - composer validate
    - vendor/bin/phpstan analyse -c phpstan.neon -l max src/

    - vendor/bin/phpunit
    - vendor/bin/phpspec run
    - vendor/bin/behat --strict -vvv --no-interaction || vendor/bin/behat --strict -vvv --tags="~@javascript" --no-interaction --rerun
after_failure:
    - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "${SYLIUS_BUILD_DIR}/*.log"
